[package]
name = "rs-rocket-tflite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6"
tflite = "0.9.7"
image = "0.24.7"
